// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.js"
// @generated from file common/common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/common.proto.
 */
export const file_common_common: GenFile = /*@__PURE__*/
  fileDesc("ChNjb21tb24vY29tbW9uLnByb3RvEgZjb21tb24iyAIKEElkTmFtZUlkZW50aWZpZXISFAoCaWQYASABKAlCCLpIBXIDsAEBEooCCgRuYW1lGAIgASgJQvsBukj3AboB7AEKC25hbWVfZm9ybWF0Ep8BTmFtZSBtdXN0IGJlIGFuIGFscGhhbnVtZXJpYyBzdHJpbmcsIGFsbG93aW5nIGh5cGhlbnMgYW5kIHVuZGVyc2NvcmVzIGJ1dCBub3QgYXMgdGhlIGZpcnN0IG9yIGxhc3QgY2hhcmFjdGVyLiBUaGUgc3RvcmVkIG5hbWUgd2lsbCBiZSBub3JtYWxpemVkIHRvIGxvd2VyIGNhc2UuGjt0aGlzLm1hdGNoZXMoJ15bYS16QS1aMC05XSg/OlthLXpBLVowLTlfLV0qW2EtekEtWjAtOV0pPyQnKXIFEAEY/QE6EbpIDiIMCgJpZAoEbmFtZRABIlIKD0lkRnFuSWRlbnRpZmllchIUCgJpZBgBIAEoCUIIukgFcgOwAQESFwoDZnFuGAIgASgJQgq6SAdyBRABiAEBOhC6SA0iCwoCaWQKA2ZxbhABIscBCghNZXRhZGF0YRIuCgpjcmVhdGVkX2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCgZsYWJlbHMYAyADKAsyHC5jb21tb24uTWV0YWRhdGEuTGFiZWxzRW50cnkaLQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJ1Cg9NZXRhZGF0YU11dGFibGUSMwoGbGFiZWxzGAMgAygLMiMuY29tbW9uLk1ldGFkYXRhTXV0YWJsZS5MYWJlbHNFbnRyeRotCgtMYWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBKn0KEk1ldGFkYXRhVXBkYXRlRW51bRIkCiBNRVRBREFUQV9VUERBVEVfRU5VTV9VTlNQRUNJRklFRBAAEh8KG01FVEFEQVRBX1VQREFURV9FTlVNX0VYVEVORBABEiAKHE1FVEFEQVRBX1VQREFURV9FTlVNX1JFUExBQ0UQAiqNAQoPQWN0aXZlU3RhdGVFbnVtEiEKHUFDVElWRV9TVEFURV9FTlVNX1VOU1BFQ0lGSUVEEAASHAoYQUNUSVZFX1NUQVRFX0VOVU1fQUNUSVZFEAESHgoaQUNUSVZFX1NUQVRFX0VOVU1fSU5BQ1RJVkUQAhIZChVBQ1RJVkVfU1RBVEVfRU5VTV9BTlkQA2IGcHJvdG8z", [file_google_protobuf_timestamp, file_buf_validate_validate]);

/**
 * @generated from message common.IdNameIdentifier
 */
export type IdNameIdentifier = Message<"common.IdNameIdentifier"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message common.IdNameIdentifier.
 * Use `create(IdNameIdentifierSchema)` to create a new message.
 */
export const IdNameIdentifierSchema: GenMessage<IdNameIdentifier> = /*@__PURE__*/
  messageDesc(file_common_common, 0);

/**
 * @generated from message common.IdFqnIdentifier
 */
export type IdFqnIdentifier = Message<"common.IdFqnIdentifier"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string fqn = 2;
   */
  fqn: string;
};

/**
 * Describes the message common.IdFqnIdentifier.
 * Use `create(IdFqnIdentifierSchema)` to create a new message.
 */
export const IdFqnIdentifierSchema: GenMessage<IdFqnIdentifier> = /*@__PURE__*/
  messageDesc(file_common_common, 1);

/**
 * Struct to uniquely identify a resource with optional additional metadata
 *
 * @generated from message common.Metadata
 */
export type Metadata = Message<"common.Metadata"> & {
  /**
   * created_at set by server (entity who created will recorded in an audit event)
   *
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * updated_at set by server (entity who updated will recorded in an audit event)
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * optional short description
   *
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message common.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_common_common, 2);

/**
 * @generated from message common.MetadataMutable
 */
export type MetadataMutable = Message<"common.MetadataMutable"> & {
  /**
   * optional labels
   *
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };
};

/**
 * Describes the message common.MetadataMutable.
 * Use `create(MetadataMutableSchema)` to create a new message.
 */
export const MetadataMutableSchema: GenMessage<MetadataMutable> = /*@__PURE__*/
  messageDesc(file_common_common, 3);

/**
 * @generated from enum common.MetadataUpdateEnum
 */
export enum MetadataUpdateEnum {
  /**
   * unspecified update type
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * only update the fields that are provided
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_EXTEND = 1;
   */
  EXTEND = 1,

  /**
   * replace the entire metadata with the provided metadata
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_REPLACE = 2;
   */
  REPLACE = 2,
}

/**
 * Describes the enum common.MetadataUpdateEnum.
 */
export const MetadataUpdateEnumSchema: GenEnum<MetadataUpdateEnum> = /*@__PURE__*/
  enumDesc(file_common_common, 0);

/**
 * buflint ENUM_VALUE_PREFIX: to make sure that C++ scoping rules aren't violated when users add new enum values to an enum in a given package
 *
 * @generated from enum common.ActiveStateEnum
 */
export enum ActiveStateEnum {
  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_ANY = 3;
   */
  ANY = 3,
}

/**
 * Describes the enum common.ActiveStateEnum.
 */
export const ActiveStateEnumSchema: GenEnum<ActiveStateEnum> = /*@__PURE__*/
  enumDesc(file_common_common, 1);

