// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts,import_extension=none"
// @generated from file common/common.proto (package common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum common.MetadataUpdateEnum
 */
export declare enum MetadataUpdateEnum {
  /**
   * unspecified update type
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * only update the fields that are provided
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_EXTEND = 1;
   */
  EXTEND = 1,

  /**
   * replace the entire metadata with the provided metadata
   *
   * @generated from enum value: METADATA_UPDATE_ENUM_REPLACE = 2;
   */
  REPLACE = 2,
}

/**
 * buflint ENUM_VALUE_PREFIX: to make sure that C++ scoping rules aren't violated when users add new enum values to an enum in a given package
 *
 * @generated from enum common.ActiveStateEnum
 */
export declare enum ActiveStateEnum {
  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: ACTIVE_STATE_ENUM_ANY = 3;
   */
  ANY = 3,
}

/**
 * Struct to uniquely identify a resource with optional additional metadata
 *
 * @generated from message common.Metadata
 */
export declare class Metadata extends Message<Metadata> {
  /**
   * created_at set by server (entity who created will recorded in an audit event)
   *
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * updated_at set by server (entity who updated will recorded in an audit event)
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * optional short description
   *
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };

  constructor(data?: PartialMessage<Metadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "common.Metadata";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Metadata;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Metadata;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Metadata;

  static equals(a: Metadata | PlainMessage<Metadata> | undefined, b: Metadata | PlainMessage<Metadata> | undefined): boolean;
}

/**
 * @generated from message common.MetadataMutable
 */
export declare class MetadataMutable extends Message<MetadataMutable> {
  /**
   * optional labels
   *
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };

  constructor(data?: PartialMessage<MetadataMutable>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "common.MetadataMutable";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MetadataMutable;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MetadataMutable;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MetadataMutable;

  static equals(a: MetadataMutable | PlainMessage<MetadataMutable> | undefined, b: MetadataMutable | PlainMessage<MetadataMutable> | undefined): boolean;
}

