// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts,import_extension=none"
// @generated from file policy/kasregistry/key_access_server_registry.proto (package policy.kasregistry, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { KeyAccessServer, PublicKey } from "../objects_pb";
import { MetadataMutable, MetadataUpdateEnum } from "../../common/common_pb";

/**
 * @generated from message policy.kasregistry.GetKeyAccessServerRequest
 */
export const GetKeyAccessServerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.GetKeyAccessServerRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message policy.kasregistry.GetKeyAccessServerResponse
 */
export const GetKeyAccessServerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.GetKeyAccessServerResponse",
  () => [
    { no: 1, name: "key_access_server", kind: "message", T: KeyAccessServer },
  ],
);

/**
 * @generated from message policy.kasregistry.ListKeyAccessServersRequest
 */
export const ListKeyAccessServersRequest = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.ListKeyAccessServersRequest",
  [],
);

/**
 * @generated from message policy.kasregistry.ListKeyAccessServersResponse
 */
export const ListKeyAccessServersResponse = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.ListKeyAccessServersResponse",
  () => [
    { no: 1, name: "key_access_servers", kind: "message", T: KeyAccessServer, repeated: true },
  ],
);

/**
 * @generated from message policy.kasregistry.CreateKeyAccessServerRequest
 */
export const CreateKeyAccessServerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.CreateKeyAccessServerRequest",
  () => [
    { no: 1, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "public_key", kind: "message", T: PublicKey },
    { no: 100, name: "metadata", kind: "message", T: MetadataMutable },
  ],
);

/**
 * @generated from message policy.kasregistry.CreateKeyAccessServerResponse
 */
export const CreateKeyAccessServerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.CreateKeyAccessServerResponse",
  () => [
    { no: 1, name: "key_access_server", kind: "message", T: KeyAccessServer },
  ],
);

/**
 * @generated from message policy.kasregistry.UpdateKeyAccessServerRequest
 */
export const UpdateKeyAccessServerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.UpdateKeyAccessServerRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "public_key", kind: "message", T: PublicKey },
    { no: 100, name: "metadata", kind: "message", T: MetadataMutable },
    { no: 101, name: "metadata_update_behavior", kind: "enum", T: proto3.getEnumType(MetadataUpdateEnum) },
  ],
);

/**
 * @generated from message policy.kasregistry.UpdateKeyAccessServerResponse
 */
export const UpdateKeyAccessServerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.UpdateKeyAccessServerResponse",
  () => [
    { no: 1, name: "key_access_server", kind: "message", T: KeyAccessServer },
  ],
);

/**
 * @generated from message policy.kasregistry.DeleteKeyAccessServerRequest
 */
export const DeleteKeyAccessServerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.DeleteKeyAccessServerRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message policy.kasregistry.DeleteKeyAccessServerResponse
 */
export const DeleteKeyAccessServerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "policy.kasregistry.DeleteKeyAccessServerResponse",
  () => [
    { no: 1, name: "key_access_server", kind: "message", T: KeyAccessServer },
  ],
);

