// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts,import_extension=none"
// @generated from file policy/kasregistry/key_access_server_registry.proto (package policy.kasregistry, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateKeyAccessServerRequest, CreateKeyAccessServerResponse, DeleteKeyAccessServerRequest, DeleteKeyAccessServerResponse, GetKeyAccessServerRequest, GetKeyAccessServerResponse, ListKeyAccessServersRequest, ListKeyAccessServersResponse, UpdateKeyAccessServerRequest, UpdateKeyAccessServerResponse } from "./key_access_server_registry_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service policy.kasregistry.KeyAccessServerRegistryService
 */
export declare const KeyAccessServerRegistryService: {
  readonly typeName: "policy.kasregistry.KeyAccessServerRegistryService",
  readonly methods: {
    /**
     * @generated from rpc policy.kasregistry.KeyAccessServerRegistryService.ListKeyAccessServers
     */
    readonly listKeyAccessServers: {
      readonly name: "ListKeyAccessServers",
      readonly I: typeof ListKeyAccessServersRequest,
      readonly O: typeof ListKeyAccessServersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.kasregistry.KeyAccessServerRegistryService.GetKeyAccessServer
     */
    readonly getKeyAccessServer: {
      readonly name: "GetKeyAccessServer",
      readonly I: typeof GetKeyAccessServerRequest,
      readonly O: typeof GetKeyAccessServerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.kasregistry.KeyAccessServerRegistryService.CreateKeyAccessServer
     */
    readonly createKeyAccessServer: {
      readonly name: "CreateKeyAccessServer",
      readonly I: typeof CreateKeyAccessServerRequest,
      readonly O: typeof CreateKeyAccessServerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.kasregistry.KeyAccessServerRegistryService.UpdateKeyAccessServer
     */
    readonly updateKeyAccessServer: {
      readonly name: "UpdateKeyAccessServer",
      readonly I: typeof UpdateKeyAccessServerRequest,
      readonly O: typeof UpdateKeyAccessServerResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.kasregistry.KeyAccessServerRegistryService.DeleteKeyAccessServer
     */
    readonly deleteKeyAccessServer: {
      readonly name: "DeleteKeyAccessServer",
      readonly I: typeof DeleteKeyAccessServerRequest,
      readonly O: typeof DeleteKeyAccessServerResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

