// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts,import_extension=none"
// @generated from file authorization/authorization.proto (package authorization, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetDecisionsByTokenRequest, GetDecisionsByTokenResponse, GetDecisionsRequest, GetDecisionsResponse, GetEntitlementsRequest, GetEntitlementsResponse } from "./authorization_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service authorization.AuthorizationService
 */
export declare const AuthorizationService: {
  readonly typeName: "authorization.AuthorizationService",
  readonly methods: {
    /**
     * @generated from rpc authorization.AuthorizationService.GetDecisions
     */
    readonly getDecisions: {
      readonly name: "GetDecisions",
      readonly I: typeof GetDecisionsRequest,
      readonly O: typeof GetDecisionsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authorization.AuthorizationService.GetDecisionsByToken
     */
    readonly getDecisionsByToken: {
      readonly name: "GetDecisionsByToken",
      readonly I: typeof GetDecisionsByTokenRequest,
      readonly O: typeof GetDecisionsByTokenResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc authorization.AuthorizationService.GetEntitlements
     */
    readonly getEntitlements: {
      readonly name: "GetEntitlements",
      readonly I: typeof GetEntitlementsRequest,
      readonly O: typeof GetEntitlementsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

