// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.js"
// @generated from file policy/selectors.proto (package policy, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file policy/selectors.proto.
 */
export const file_policy_selectors: GenFile = /*@__PURE__*/
  fileDesc("ChZwb2xpY3kvc2VsZWN0b3JzLnByb3RvEgZwb2xpY3ki4gIKGkF0dHJpYnV0ZU5hbWVzcGFjZVNlbGVjdG9yEk0KD3dpdGhfYXR0cmlidXRlcxgKIAEoCzI0LnBvbGljeS5BdHRyaWJ1dGVOYW1lc3BhY2VTZWxlY3Rvci5BdHRyaWJ1dGVTZWxlY3Rvchr0AQoRQXR0cmlidXRlU2VsZWN0b3ISHgoWd2l0aF9rZXlfYWNjZXNzX2dyYW50cxgBIAEoCBJXCgt3aXRoX3ZhbHVlcxgKIAEoCzJCLnBvbGljeS5BdHRyaWJ1dGVOYW1lc3BhY2VTZWxlY3Rvci5BdHRyaWJ1dGVTZWxlY3Rvci5WYWx1ZVNlbGVjdG9yGmYKDVZhbHVlU2VsZWN0b3ISHgoWd2l0aF9rZXlfYWNjZXNzX2dyYW50cxgBIAEoCBIZChF3aXRoX3N1YmplY3RfbWFwcxgCIAEoCBIaChJ3aXRoX3Jlc291cmNlX21hcHMYAyABKAgi0QIKG0F0dHJpYnV0ZURlZmluaXRpb25TZWxlY3RvchIeChZ3aXRoX2tleV9hY2Nlc3NfZ3JhbnRzGAEgASgIEk0KDndpdGhfbmFtZXNwYWNlGAogASgLMjUucG9saWN5LkF0dHJpYnV0ZURlZmluaXRpb25TZWxlY3Rvci5OYW1lc3BhY2VTZWxlY3RvchJGCgt3aXRoX3ZhbHVlcxgLIAEoCzIxLnBvbGljeS5BdHRyaWJ1dGVEZWZpbml0aW9uU2VsZWN0b3IuVmFsdWVTZWxlY3RvchoTChFOYW1lc3BhY2VTZWxlY3RvchpmCg1WYWx1ZVNlbGVjdG9yEh4KFndpdGhfa2V5X2FjY2Vzc19ncmFudHMYASABKAgSGQoRd2l0aF9zdWJqZWN0X21hcHMYAiABKAgSGgoSd2l0aF9yZXNvdXJjZV9tYXBzGAMgASgIIuACChZBdHRyaWJ1dGVWYWx1ZVNlbGVjdG9yEh4KFndpdGhfa2V5X2FjY2Vzc19ncmFudHMYASABKAgSGQoRd2l0aF9zdWJqZWN0X21hcHMYAiABKAgSGgoSd2l0aF9yZXNvdXJjZV9tYXBzGAMgASgIEkgKDndpdGhfYXR0cmlidXRlGAogASgLMjAucG9saWN5LkF0dHJpYnV0ZVZhbHVlU2VsZWN0b3IuQXR0cmlidXRlU2VsZWN0b3IapAEKEUF0dHJpYnV0ZVNlbGVjdG9yEh4KFndpdGhfa2V5X2FjY2Vzc19ncmFudHMYASABKAgSWgoOd2l0aF9uYW1lc3BhY2UYCiABKAsyQi5wb2xpY3kuQXR0cmlidXRlVmFsdWVTZWxlY3Rvci5BdHRyaWJ1dGVTZWxlY3Rvci5OYW1lc3BhY2VTZWxlY3RvchoTChFOYW1lc3BhY2VTZWxlY3RvciIsCgtQYWdlUmVxdWVzdBINCgVsaW1pdBgBIAEoBRIOCgZvZmZzZXQYAiABKAUiSgoMUGFnZVJlc3BvbnNlEhYKDmN1cnJlbnRfb2Zmc2V0GAEgASgFEhMKC25leHRfb2Zmc2V0GAIgASgFEg0KBXRvdGFsGAMgASgFYgZwcm90bzM");

/**
 * @generated from message policy.AttributeNamespaceSelector
 */
export type AttributeNamespaceSelector = Message<"policy.AttributeNamespaceSelector"> & {
  /**
   * @generated from field: policy.AttributeNamespaceSelector.AttributeSelector with_attributes = 10;
   */
  withAttributes?: AttributeNamespaceSelector_AttributeSelector;
};

/**
 * Describes the message policy.AttributeNamespaceSelector.
 * Use `create(AttributeNamespaceSelectorSchema)` to create a new message.
 */
export const AttributeNamespaceSelectorSchema: GenMessage<AttributeNamespaceSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 0);

/**
 * @generated from message policy.AttributeNamespaceSelector.AttributeSelector
 */
export type AttributeNamespaceSelector_AttributeSelector = Message<"policy.AttributeNamespaceSelector.AttributeSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: policy.AttributeNamespaceSelector.AttributeSelector.ValueSelector with_values = 10;
   */
  withValues?: AttributeNamespaceSelector_AttributeSelector_ValueSelector;
};

/**
 * Describes the message policy.AttributeNamespaceSelector.AttributeSelector.
 * Use `create(AttributeNamespaceSelector_AttributeSelectorSchema)` to create a new message.
 */
export const AttributeNamespaceSelector_AttributeSelectorSchema: GenMessage<AttributeNamespaceSelector_AttributeSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 0, 0);

/**
 * @generated from message policy.AttributeNamespaceSelector.AttributeSelector.ValueSelector
 */
export type AttributeNamespaceSelector_AttributeSelector_ValueSelector = Message<"policy.AttributeNamespaceSelector.AttributeSelector.ValueSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: bool with_subject_maps = 2;
   */
  withSubjectMaps: boolean;

  /**
   * @generated from field: bool with_resource_maps = 3;
   */
  withResourceMaps: boolean;
};

/**
 * Describes the message policy.AttributeNamespaceSelector.AttributeSelector.ValueSelector.
 * Use `create(AttributeNamespaceSelector_AttributeSelector_ValueSelectorSchema)` to create a new message.
 */
export const AttributeNamespaceSelector_AttributeSelector_ValueSelectorSchema: GenMessage<AttributeNamespaceSelector_AttributeSelector_ValueSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 0, 0, 0);

/**
 * @generated from message policy.AttributeDefinitionSelector
 */
export type AttributeDefinitionSelector = Message<"policy.AttributeDefinitionSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: policy.AttributeDefinitionSelector.NamespaceSelector with_namespace = 10;
   */
  withNamespace?: AttributeDefinitionSelector_NamespaceSelector;

  /**
   * @generated from field: policy.AttributeDefinitionSelector.ValueSelector with_values = 11;
   */
  withValues?: AttributeDefinitionSelector_ValueSelector;
};

/**
 * Describes the message policy.AttributeDefinitionSelector.
 * Use `create(AttributeDefinitionSelectorSchema)` to create a new message.
 */
export const AttributeDefinitionSelectorSchema: GenMessage<AttributeDefinitionSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 1);

/**
 * @generated from message policy.AttributeDefinitionSelector.NamespaceSelector
 */
export type AttributeDefinitionSelector_NamespaceSelector = Message<"policy.AttributeDefinitionSelector.NamespaceSelector"> & {
};

/**
 * Describes the message policy.AttributeDefinitionSelector.NamespaceSelector.
 * Use `create(AttributeDefinitionSelector_NamespaceSelectorSchema)` to create a new message.
 */
export const AttributeDefinitionSelector_NamespaceSelectorSchema: GenMessage<AttributeDefinitionSelector_NamespaceSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 1, 0);

/**
 * @generated from message policy.AttributeDefinitionSelector.ValueSelector
 */
export type AttributeDefinitionSelector_ValueSelector = Message<"policy.AttributeDefinitionSelector.ValueSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: bool with_subject_maps = 2;
   */
  withSubjectMaps: boolean;

  /**
   * @generated from field: bool with_resource_maps = 3;
   */
  withResourceMaps: boolean;
};

/**
 * Describes the message policy.AttributeDefinitionSelector.ValueSelector.
 * Use `create(AttributeDefinitionSelector_ValueSelectorSchema)` to create a new message.
 */
export const AttributeDefinitionSelector_ValueSelectorSchema: GenMessage<AttributeDefinitionSelector_ValueSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 1, 1);

/**
 * @generated from message policy.AttributeValueSelector
 */
export type AttributeValueSelector = Message<"policy.AttributeValueSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: bool with_subject_maps = 2;
   */
  withSubjectMaps: boolean;

  /**
   * @generated from field: bool with_resource_maps = 3;
   */
  withResourceMaps: boolean;

  /**
   * @generated from field: policy.AttributeValueSelector.AttributeSelector with_attribute = 10;
   */
  withAttribute?: AttributeValueSelector_AttributeSelector;
};

/**
 * Describes the message policy.AttributeValueSelector.
 * Use `create(AttributeValueSelectorSchema)` to create a new message.
 */
export const AttributeValueSelectorSchema: GenMessage<AttributeValueSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 2);

/**
 * @generated from message policy.AttributeValueSelector.AttributeSelector
 */
export type AttributeValueSelector_AttributeSelector = Message<"policy.AttributeValueSelector.AttributeSelector"> & {
  /**
   * Deprecated
   *
   * @generated from field: bool with_key_access_grants = 1;
   */
  withKeyAccessGrants: boolean;

  /**
   * @generated from field: policy.AttributeValueSelector.AttributeSelector.NamespaceSelector with_namespace = 10;
   */
  withNamespace?: AttributeValueSelector_AttributeSelector_NamespaceSelector;
};

/**
 * Describes the message policy.AttributeValueSelector.AttributeSelector.
 * Use `create(AttributeValueSelector_AttributeSelectorSchema)` to create a new message.
 */
export const AttributeValueSelector_AttributeSelectorSchema: GenMessage<AttributeValueSelector_AttributeSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 2, 0);

/**
 * @generated from message policy.AttributeValueSelector.AttributeSelector.NamespaceSelector
 */
export type AttributeValueSelector_AttributeSelector_NamespaceSelector = Message<"policy.AttributeValueSelector.AttributeSelector.NamespaceSelector"> & {
};

/**
 * Describes the message policy.AttributeValueSelector.AttributeSelector.NamespaceSelector.
 * Use `create(AttributeValueSelector_AttributeSelector_NamespaceSelectorSchema)` to create a new message.
 */
export const AttributeValueSelector_AttributeSelector_NamespaceSelectorSchema: GenMessage<AttributeValueSelector_AttributeSelector_NamespaceSelector> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 2, 0, 0);

/**
 * @generated from message policy.PageRequest
 */
export type PageRequest = Message<"policy.PageRequest"> & {
  /**
   * Optional
   * Set to configured default limit if not provided
   * Maximum limit set in platform config and enforced by services
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * Optional
   * Defaulted if not provided
   *
   * @generated from field: int32 offset = 2;
   */
  offset: number;
};

/**
 * Describes the message policy.PageRequest.
 * Use `create(PageRequestSchema)` to create a new message.
 */
export const PageRequestSchema: GenMessage<PageRequest> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 3);

/**
 * @generated from message policy.PageResponse
 */
export type PageResponse = Message<"policy.PageResponse"> & {
  /**
   * Requested pagination offset
   *
   * @generated from field: int32 current_offset = 1;
   */
  currentOffset: number;

  /**
   * Calculated with request limit + offset or defaults
   * Empty when none remain after current page
   *
   * @generated from field: int32 next_offset = 2;
   */
  nextOffset: number;

  /**
   * Total count of entire list
   *
   * @generated from field: int32 total = 3;
   */
  total: number;
};

/**
 * Describes the message policy.PageResponse.
 * Use `create(PageResponseSchema)` to create a new message.
 */
export const PageResponseSchema: GenMessage<PageResponse> = /*@__PURE__*/
  messageDesc(file_policy_selectors, 4);

