// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts,import_extension=none"
// @generated from file policy/resourcemapping/resource_mapping.proto (package policy.resourcemapping, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ResourceMapping } from "../objects_pb";
import type { MetadataMutable, MetadataUpdateEnum } from "../../common/common_pb";

/**
 * @generated from message policy.resourcemapping.ListResourceMappingsRequest
 */
export declare class ListResourceMappingsRequest extends Message<ListResourceMappingsRequest> {
  constructor(data?: PartialMessage<ListResourceMappingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.ListResourceMappingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResourceMappingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResourceMappingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResourceMappingsRequest;

  static equals(a: ListResourceMappingsRequest | PlainMessage<ListResourceMappingsRequest> | undefined, b: ListResourceMappingsRequest | PlainMessage<ListResourceMappingsRequest> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.ListResourceMappingsResponse
 */
export declare class ListResourceMappingsResponse extends Message<ListResourceMappingsResponse> {
  /**
   * @generated from field: repeated policy.ResourceMapping resource_mappings = 1;
   */
  resourceMappings: ResourceMapping[];

  constructor(data?: PartialMessage<ListResourceMappingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.ListResourceMappingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResourceMappingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResourceMappingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResourceMappingsResponse;

  static equals(a: ListResourceMappingsResponse | PlainMessage<ListResourceMappingsResponse> | undefined, b: ListResourceMappingsResponse | PlainMessage<ListResourceMappingsResponse> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.GetResourceMappingRequest
 */
export declare class GetResourceMappingRequest extends Message<GetResourceMappingRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetResourceMappingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.GetResourceMappingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResourceMappingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResourceMappingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResourceMappingRequest;

  static equals(a: GetResourceMappingRequest | PlainMessage<GetResourceMappingRequest> | undefined, b: GetResourceMappingRequest | PlainMessage<GetResourceMappingRequest> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.GetResourceMappingResponse
 */
export declare class GetResourceMappingResponse extends Message<GetResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<GetResourceMappingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.GetResourceMappingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResourceMappingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResourceMappingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResourceMappingResponse;

  static equals(a: GetResourceMappingResponse | PlainMessage<GetResourceMappingResponse> | undefined, b: GetResourceMappingResponse | PlainMessage<GetResourceMappingResponse> | undefined): boolean;
}

/**
 *
 * ### Request
 *
 * grpcurl -plaintext -d @ localhost:8080 policy.resourcemapping.ResourceMappingService/CreateResourceMapping <<EOM
 * {
 * "mapping": {
 * "name": "Classification",
 * "attribute_value_id": "12345678-1234-1234-1234-123456789012",
 * "terms": ["CONFIDENTIAL", "CONTROLLED UNCLASSIFIED", "OFFICIAL-SENSITIVE", "CUI", "C"]
 * }
 * }
 * EOM
 *
 * ### Response
 *
 * {
 * "mapping": {
 * "metadata": {
 * "id": "12345678-1234-1234-1234-123456789012",
 * "created_at": "2020-01-01T00:00:00Z",
 * "updated_at": "2020-01-01T00:00:00Z"
 * },
 * "name": "Classification",
 * "attribute_value_id": "12345678-1234-1234-1234-123456789012",
 * "terms": ["CONFIDENTIAL", "CONTROLLED UNCLASSIFIED", "OFFICIAL-SENSITIVE", "CUI", "C"]
 * }
 * }
 *
 *
 * @generated from message policy.resourcemapping.CreateResourceMappingRequest
 */
export declare class CreateResourceMappingRequest extends Message<CreateResourceMappingRequest> {
  /**
   * Required
   *
   * @generated from field: string attribute_value_id = 1;
   */
  attributeValueId: string;

  /**
   * @generated from field: repeated string terms = 2;
   */
  terms: string[];

  /**
   * Optional
   *
   * @generated from field: common.MetadataMutable metadata = 100;
   */
  metadata?: MetadataMutable;

  constructor(data?: PartialMessage<CreateResourceMappingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.CreateResourceMappingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateResourceMappingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateResourceMappingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateResourceMappingRequest;

  static equals(a: CreateResourceMappingRequest | PlainMessage<CreateResourceMappingRequest> | undefined, b: CreateResourceMappingRequest | PlainMessage<CreateResourceMappingRequest> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.CreateResourceMappingResponse
 */
export declare class CreateResourceMappingResponse extends Message<CreateResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<CreateResourceMappingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.CreateResourceMappingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateResourceMappingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateResourceMappingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateResourceMappingResponse;

  static equals(a: CreateResourceMappingResponse | PlainMessage<CreateResourceMappingResponse> | undefined, b: CreateResourceMappingResponse | PlainMessage<CreateResourceMappingResponse> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.UpdateResourceMappingRequest
 */
export declare class UpdateResourceMappingRequest extends Message<UpdateResourceMappingRequest> {
  /**
   * Required
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Optional
   *
   * @generated from field: string attribute_value_id = 4;
   */
  attributeValueId: string;

  /**
   * @generated from field: repeated string terms = 5;
   */
  terms: string[];

  /**
   * Common Metadata
   *
   * @generated from field: common.MetadataMutable metadata = 100;
   */
  metadata?: MetadataMutable;

  /**
   * @generated from field: common.MetadataUpdateEnum metadata_update_behavior = 101;
   */
  metadataUpdateBehavior: MetadataUpdateEnum;

  constructor(data?: PartialMessage<UpdateResourceMappingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.UpdateResourceMappingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateResourceMappingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateResourceMappingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateResourceMappingRequest;

  static equals(a: UpdateResourceMappingRequest | PlainMessage<UpdateResourceMappingRequest> | undefined, b: UpdateResourceMappingRequest | PlainMessage<UpdateResourceMappingRequest> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.UpdateResourceMappingResponse
 */
export declare class UpdateResourceMappingResponse extends Message<UpdateResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<UpdateResourceMappingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.UpdateResourceMappingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateResourceMappingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateResourceMappingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateResourceMappingResponse;

  static equals(a: UpdateResourceMappingResponse | PlainMessage<UpdateResourceMappingResponse> | undefined, b: UpdateResourceMappingResponse | PlainMessage<UpdateResourceMappingResponse> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.DeleteResourceMappingRequest
 */
export declare class DeleteResourceMappingRequest extends Message<DeleteResourceMappingRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<DeleteResourceMappingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.DeleteResourceMappingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResourceMappingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResourceMappingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResourceMappingRequest;

  static equals(a: DeleteResourceMappingRequest | PlainMessage<DeleteResourceMappingRequest> | undefined, b: DeleteResourceMappingRequest | PlainMessage<DeleteResourceMappingRequest> | undefined): boolean;
}

/**
 * @generated from message policy.resourcemapping.DeleteResourceMappingResponse
 */
export declare class DeleteResourceMappingResponse extends Message<DeleteResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<DeleteResourceMappingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "policy.resourcemapping.DeleteResourceMappingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResourceMappingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResourceMappingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResourceMappingResponse;

  static equals(a: DeleteResourceMappingResponse | PlainMessage<DeleteResourceMappingResponse> | undefined, b: DeleteResourceMappingResponse | PlainMessage<DeleteResourceMappingResponse> | undefined): boolean;
}

