// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file policy/resourcemapping/resource_mapping.proto (package policy.resourcemapping, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ResourceMapping } from "../objects_pb.js";
import { MetadataMutable, MetadataUpdateEnum } from "../../common/common_pb.js";

/**
 * @generated from message policy.resourcemapping.ListResourceMappingsRequest
 */
export class ListResourceMappingsRequest extends Message<ListResourceMappingsRequest> {
  constructor(data?: PartialMessage<ListResourceMappingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.ListResourceMappingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResourceMappingsRequest {
    return new ListResourceMappingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResourceMappingsRequest {
    return new ListResourceMappingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResourceMappingsRequest {
    return new ListResourceMappingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListResourceMappingsRequest | PlainMessage<ListResourceMappingsRequest> | undefined, b: ListResourceMappingsRequest | PlainMessage<ListResourceMappingsRequest> | undefined): boolean {
    return proto3.util.equals(ListResourceMappingsRequest, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.ListResourceMappingsResponse
 */
export class ListResourceMappingsResponse extends Message<ListResourceMappingsResponse> {
  /**
   * @generated from field: repeated policy.ResourceMapping resource_mappings = 1;
   */
  resourceMappings: ResourceMapping[] = [];

  constructor(data?: PartialMessage<ListResourceMappingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.ListResourceMappingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource_mappings", kind: "message", T: ResourceMapping, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResourceMappingsResponse {
    return new ListResourceMappingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResourceMappingsResponse {
    return new ListResourceMappingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResourceMappingsResponse {
    return new ListResourceMappingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListResourceMappingsResponse | PlainMessage<ListResourceMappingsResponse> | undefined, b: ListResourceMappingsResponse | PlainMessage<ListResourceMappingsResponse> | undefined): boolean {
    return proto3.util.equals(ListResourceMappingsResponse, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.GetResourceMappingRequest
 */
export class GetResourceMappingRequest extends Message<GetResourceMappingRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetResourceMappingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.GetResourceMappingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResourceMappingRequest {
    return new GetResourceMappingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResourceMappingRequest {
    return new GetResourceMappingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResourceMappingRequest {
    return new GetResourceMappingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetResourceMappingRequest | PlainMessage<GetResourceMappingRequest> | undefined, b: GetResourceMappingRequest | PlainMessage<GetResourceMappingRequest> | undefined): boolean {
    return proto3.util.equals(GetResourceMappingRequest, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.GetResourceMappingResponse
 */
export class GetResourceMappingResponse extends Message<GetResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<GetResourceMappingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.GetResourceMappingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource_mapping", kind: "message", T: ResourceMapping },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResourceMappingResponse {
    return new GetResourceMappingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResourceMappingResponse {
    return new GetResourceMappingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResourceMappingResponse {
    return new GetResourceMappingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetResourceMappingResponse | PlainMessage<GetResourceMappingResponse> | undefined, b: GetResourceMappingResponse | PlainMessage<GetResourceMappingResponse> | undefined): boolean {
    return proto3.util.equals(GetResourceMappingResponse, a, b);
  }
}

/**
 *
 * ### Request
 *
 * grpcurl -plaintext -d @ localhost:8080 policy.resourcemapping.ResourceMappingService/CreateResourceMapping <<EOM
 * {
 * "mapping": {
 * "name": "Classification",
 * "attribute_value_id": "12345678-1234-1234-1234-123456789012",
 * "terms": ["CONFIDENTIAL", "CONTROLLED UNCLASSIFIED", "OFFICIAL-SENSITIVE", "CUI", "C"]
 * }
 * }
 * EOM
 *
 * ### Response
 *
 * {
 * "mapping": {
 * "metadata": {
 * "id": "12345678-1234-1234-1234-123456789012",
 * "created_at": "2020-01-01T00:00:00Z",
 * "updated_at": "2020-01-01T00:00:00Z"
 * },
 * "name": "Classification",
 * "attribute_value_id": "12345678-1234-1234-1234-123456789012",
 * "terms": ["CONFIDENTIAL", "CONTROLLED UNCLASSIFIED", "OFFICIAL-SENSITIVE", "CUI", "C"]
 * }
 * }
 *
 *
 * @generated from message policy.resourcemapping.CreateResourceMappingRequest
 */
export class CreateResourceMappingRequest extends Message<CreateResourceMappingRequest> {
  /**
   * Required
   *
   * @generated from field: string attribute_value_id = 1;
   */
  attributeValueId = "";

  /**
   * @generated from field: repeated string terms = 2;
   */
  terms: string[] = [];

  /**
   * Optional
   *
   * @generated from field: common.MetadataMutable metadata = 100;
   */
  metadata?: MetadataMutable;

  constructor(data?: PartialMessage<CreateResourceMappingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.CreateResourceMappingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "attribute_value_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "terms", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 100, name: "metadata", kind: "message", T: MetadataMutable },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateResourceMappingRequest {
    return new CreateResourceMappingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateResourceMappingRequest {
    return new CreateResourceMappingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateResourceMappingRequest {
    return new CreateResourceMappingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateResourceMappingRequest | PlainMessage<CreateResourceMappingRequest> | undefined, b: CreateResourceMappingRequest | PlainMessage<CreateResourceMappingRequest> | undefined): boolean {
    return proto3.util.equals(CreateResourceMappingRequest, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.CreateResourceMappingResponse
 */
export class CreateResourceMappingResponse extends Message<CreateResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<CreateResourceMappingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.CreateResourceMappingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource_mapping", kind: "message", T: ResourceMapping },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateResourceMappingResponse {
    return new CreateResourceMappingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateResourceMappingResponse {
    return new CreateResourceMappingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateResourceMappingResponse {
    return new CreateResourceMappingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateResourceMappingResponse | PlainMessage<CreateResourceMappingResponse> | undefined, b: CreateResourceMappingResponse | PlainMessage<CreateResourceMappingResponse> | undefined): boolean {
    return proto3.util.equals(CreateResourceMappingResponse, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.UpdateResourceMappingRequest
 */
export class UpdateResourceMappingRequest extends Message<UpdateResourceMappingRequest> {
  /**
   * Required
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Optional
   *
   * @generated from field: string attribute_value_id = 4;
   */
  attributeValueId = "";

  /**
   * @generated from field: repeated string terms = 5;
   */
  terms: string[] = [];

  /**
   * Common Metadata
   *
   * @generated from field: common.MetadataMutable metadata = 100;
   */
  metadata?: MetadataMutable;

  /**
   * @generated from field: common.MetadataUpdateEnum metadata_update_behavior = 101;
   */
  metadataUpdateBehavior = MetadataUpdateEnum.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateResourceMappingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.UpdateResourceMappingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "attribute_value_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "terms", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 100, name: "metadata", kind: "message", T: MetadataMutable },
    { no: 101, name: "metadata_update_behavior", kind: "enum", T: proto3.getEnumType(MetadataUpdateEnum) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateResourceMappingRequest {
    return new UpdateResourceMappingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateResourceMappingRequest {
    return new UpdateResourceMappingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateResourceMappingRequest {
    return new UpdateResourceMappingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateResourceMappingRequest | PlainMessage<UpdateResourceMappingRequest> | undefined, b: UpdateResourceMappingRequest | PlainMessage<UpdateResourceMappingRequest> | undefined): boolean {
    return proto3.util.equals(UpdateResourceMappingRequest, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.UpdateResourceMappingResponse
 */
export class UpdateResourceMappingResponse extends Message<UpdateResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<UpdateResourceMappingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.UpdateResourceMappingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource_mapping", kind: "message", T: ResourceMapping },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateResourceMappingResponse {
    return new UpdateResourceMappingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateResourceMappingResponse {
    return new UpdateResourceMappingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateResourceMappingResponse {
    return new UpdateResourceMappingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateResourceMappingResponse | PlainMessage<UpdateResourceMappingResponse> | undefined, b: UpdateResourceMappingResponse | PlainMessage<UpdateResourceMappingResponse> | undefined): boolean {
    return proto3.util.equals(UpdateResourceMappingResponse, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.DeleteResourceMappingRequest
 */
export class DeleteResourceMappingRequest extends Message<DeleteResourceMappingRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteResourceMappingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.DeleteResourceMappingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResourceMappingRequest {
    return new DeleteResourceMappingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResourceMappingRequest {
    return new DeleteResourceMappingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResourceMappingRequest {
    return new DeleteResourceMappingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteResourceMappingRequest | PlainMessage<DeleteResourceMappingRequest> | undefined, b: DeleteResourceMappingRequest | PlainMessage<DeleteResourceMappingRequest> | undefined): boolean {
    return proto3.util.equals(DeleteResourceMappingRequest, a, b);
  }
}

/**
 * @generated from message policy.resourcemapping.DeleteResourceMappingResponse
 */
export class DeleteResourceMappingResponse extends Message<DeleteResourceMappingResponse> {
  /**
   * @generated from field: policy.ResourceMapping resource_mapping = 1;
   */
  resourceMapping?: ResourceMapping;

  constructor(data?: PartialMessage<DeleteResourceMappingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "policy.resourcemapping.DeleteResourceMappingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "resource_mapping", kind: "message", T: ResourceMapping },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResourceMappingResponse {
    return new DeleteResourceMappingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResourceMappingResponse {
    return new DeleteResourceMappingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResourceMappingResponse {
    return new DeleteResourceMappingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteResourceMappingResponse | PlainMessage<DeleteResourceMappingResponse> | undefined, b: DeleteResourceMappingResponse | PlainMessage<DeleteResourceMappingResponse> | undefined): boolean {
    return proto3.util.equals(DeleteResourceMappingResponse, a, b);
  }
}

