// @generated by protoc-gen-es v1.9.0 with parameter "target=ts"
// @generated from file wellknownconfiguration/wellknown_configuration.proto (package wellknownconfiguration, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf';
import { Message, proto3, Struct } from '@bufbuild/protobuf';

/**
 * @generated from message wellknownconfiguration.WellKnownConfig
 */
export class WellKnownConfig extends Message<WellKnownConfig> {
  /**
   * @generated from field: map<string, google.protobuf.Struct> configuration = 1;
   */
  configuration: { [key: string]: Struct } = {};

  constructor(data?: PartialMessage<WellKnownConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'wellknownconfiguration.WellKnownConfig';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'configuration',
      kind: 'map',
      K: 9 /* ScalarType.STRING */,
      V: { kind: 'message', T: Struct },
    },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WellKnownConfig {
    return new WellKnownConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WellKnownConfig {
    return new WellKnownConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WellKnownConfig {
    return new WellKnownConfig().fromJsonString(jsonString, options);
  }

  static equals(
    a: WellKnownConfig | PlainMessage<WellKnownConfig> | undefined,
    b: WellKnownConfig | PlainMessage<WellKnownConfig> | undefined
  ): boolean {
    return proto3.util.equals(WellKnownConfig, a, b);
  }
}

/**
 * @generated from message wellknownconfiguration.GetWellKnownConfigurationRequest
 */
export class GetWellKnownConfigurationRequest extends Message<GetWellKnownConfigurationRequest> {
  constructor(data?: PartialMessage<GetWellKnownConfigurationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'wellknownconfiguration.GetWellKnownConfigurationRequest';
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): GetWellKnownConfigurationRequest {
    return new GetWellKnownConfigurationRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): GetWellKnownConfigurationRequest {
    return new GetWellKnownConfigurationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): GetWellKnownConfigurationRequest {
    return new GetWellKnownConfigurationRequest().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | GetWellKnownConfigurationRequest
      | PlainMessage<GetWellKnownConfigurationRequest>
      | undefined,
    b: GetWellKnownConfigurationRequest | PlainMessage<GetWellKnownConfigurationRequest> | undefined
  ): boolean {
    return proto3.util.equals(GetWellKnownConfigurationRequest, a, b);
  }
}

/**
 * @generated from message wellknownconfiguration.GetWellKnownConfigurationResponse
 */
export class GetWellKnownConfigurationResponse extends Message<GetWellKnownConfigurationResponse> {
  /**
   * @generated from field: google.protobuf.Struct configuration = 1;
   */
  configuration?: Struct;

  constructor(data?: PartialMessage<GetWellKnownConfigurationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'wellknownconfiguration.GetWellKnownConfigurationResponse';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'configuration', kind: 'message', T: Struct },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): GetWellKnownConfigurationResponse {
    return new GetWellKnownConfigurationResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): GetWellKnownConfigurationResponse {
    return new GetWellKnownConfigurationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): GetWellKnownConfigurationResponse {
    return new GetWellKnownConfigurationResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | GetWellKnownConfigurationResponse
      | PlainMessage<GetWellKnownConfigurationResponse>
      | undefined,
    b:
      | GetWellKnownConfigurationResponse
      | PlainMessage<GetWellKnownConfigurationResponse>
      | undefined
  ): boolean {
    return proto3.util.equals(GetWellKnownConfigurationResponse, a, b);
  }
}
