import { expect } from 'chai';

import { encodeArrayBuffer } from '../../../src/encodings/base64.js';
import type { CentralDirectory } from '../../../tdf3/src/utils/zip-reader.js';
import {
  assertManifestWithinSizeLimit,
  MANIFEST_MAX_SIZE,
  parseCDBuffer,
  readUInt64LE,
  ZipReader,
} from '../../../tdf3/src/utils/zip-reader.js';
import { ZipWriter, dateToDosDateTime, writeUInt64LE } from '../../../tdf3/src/utils/zip-writer.js';

describe('zip utilities', () => {
  describe('dateToDos', () => {
    it('zero', () => {
      const dosEpochStart = new Date('1980-01-01T00:00:00');
      const { date, time } = dateToDosDateTime(dosEpochStart);
      // DOS used 1-indexed day-of-month and month-of-year fields.

      expect(date).to.equal(0x1 | (0x1 << 5));
      expect(time).to.equal(0);
    });
    it('ninteen ninety nine', () => {
      const dosEpochStart = new Date('1999-12-31T23:59:59');
      const { date, time } = dateToDosDateTime(dosEpochStart);

      expect(date).to.equal(31 | (12 << 5) | (19 << 9));
      // File modificaiton stamps only had two-second granularity.

      expect(time).to.equal(29 | (59 << 5) | (23 << 11));
    });
  });

  describe('assertManifestWithinSizeLimit', () => {
    it('allows a manifest at or under the limit', () => {
      expect(() => assertManifestWithinSizeLimit(MANIFEST_MAX_SIZE, 1)).to.not.throw();
      expect(() => assertManifestWithinSizeLimit(0, 0)).to.not.throw();
    });

    it('rejects a manifest that would exceed the limit, before it is written', () => {
      expect(() => assertManifestWithinSizeLimit(MANIFEST_MAX_SIZE + 1, 291_000)).to.throw(
        /Manifest too large to write.*291,000 segments.*increase segmentSize/
      );
    });
  });

  describe('writeUInt64LE', () => {
    it('not too different', () => {
      // allocate a new uint8array with 8 bytes
      const b0 = new Uint8Array(8);
      new DataView(b0.buffer).setBigUint64(0, BigInt(1), true);
      const b1 = new Uint8Array(8);
      writeUInt64LE(b1, 1, 0);
      expect(b1).to.eql(b0);
    });
    it('unsafe ints throw', () => {
      expect(() => writeUInt64LE(new Uint8Array(0), 2 ** 54, 0)).to.throw(/unsafe number/);
    });
  });
  describe('readUInt64LE', () => {
    it('one', () => {
      const b0 = new Uint8Array(8);
      new DataView(b0.buffer).setBigUint64(0, 1n, true);
      expect(readUInt64LE(b0, 0)).to.equal(1);
    });
    it('unsafe ints throw', () => {
      const b0 = new Uint8Array(8);
      new DataView(b0.buffer).setBigUint64(0, 9007199254740992n, true);
      expect(() => readUInt64LE(b0, 0)).to.throw(/exceeds/);
    });
  });

  describe('localFileHeaders', () => {
    it('standard', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = false;
      const headerBuffer = zipWriter.getLocalFileHeader(
        'Hey.txt',
        0x1337,
        5,
        500,
        new Date('1980-01-01T00:00:00')
      );
      expect(encodeArrayBuffer(headerBuffer.buffer)).to.equal(
        'UEsDBBQACAgAAAAAIQA3EwAABQAAAPQBAAAHAAAASGV5LnR4dA=='
      );
    });
    it('zip64', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = true;
      const headerBuffer = zipWriter.getLocalFileHeader(
        'Hey.txt',
        0x1337,
        5,
        500,
        new Date('1980-01-01T00:00:00')
      );
      expect(encodeArrayBuffer(headerBuffer.buffer)).to.equal(
        'UEsDBBQACAgAAAAAIQA3EwAA//////////8HABwASGV5LnR4dAEAGAAFAAAAAAAAAPQBAAAAAAAAAAAAAAAAAAA='
      );
    });
  });

  describe('dataDescriptors', () => {
    it('standard', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = false;
      const descriptorBuffer = zipWriter.writeDataDescriptor(0x1337, 500);
      expect(encodeArrayBuffer(descriptorBuffer.buffer)).to.equal('UEsHCDcTAAD0AQAA9AEAAA==');
    });
    it('zip64', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = true;
      const descriptorBuffer = zipWriter.writeDataDescriptor(0x1337, 500);
      expect(encodeArrayBuffer(descriptorBuffer.buffer)).to.equal(
        'UEsHCDcTAAD0AQAAAAAAAPQBAAAAAAAA'
      );
    });
  });

  // CHARACTERISTIC TESTS of zip files.
  // TODO(PLAT-1134) Include samples generated by c++ sdk
  describe('centralDirectoryRecords', () => {
    it('standard', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = false;
      const cdrBuffer = zipWriter.writeCentralDirectoryRecord(
        500,
        'Hey.txt',
        2000,
        0x1337,
        0x81a40000,
        new Date('1980-01-01T00:00:00')
      );
      expect(parseCDBuffer(cdrBuffer)).to.deep.include({
        compressedSize: 500,
        uncompressedSize: 500,
        fileName: 'Hey.txt',
        crc32: 0x1337,
        relativeOffsetOfLocalHeader: 2000,
        externalFileAttributes: 2175008768,
        lastModFileDate: 33,
        lastModFileTime: 0,
      });
      expect(encodeArrayBuffer(cdrBuffer.buffer)).to.equal(
        'UEsBAj8DFAAICAAAAAAhADcTAAD0AQAA9AEAAAcAAAAAAAAAAAAAAKSB0AcAAEhleS50eHQ='
      );
    });
    it('zip64', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = true;
      const cdrBuffer = zipWriter.writeCentralDirectoryRecord(
        2 ** 50,
        'Hey.txt',
        2000,
        0x1337,
        0x81a40000,
        new Date('1980-01-01T00:00:00')
      );
      expect(parseCDBuffer(cdrBuffer)).to.deep.include({
        compressedSize: 2 ** 50,
        uncompressedSize: 2 ** 50,
        fileName: 'Hey.txt',
        crc32: 0x1337,
        relativeOffsetOfLocalHeader: 2000,
        externalFileAttributes: 2175008768,
        lastModFileDate: 33,
        lastModFileTime: 0,
      });
      expect(encodeArrayBuffer(cdrBuffer.buffer)).to.equal(
        'UEsBAj8DLQAICAAAAAAhADcTAAD//////////wcAHAAAAAAAAAAAAKSB/////0hleS50eHQBABgAAAAAAAAABAAAAAAAAAAEANAHAAAAAAAA'
      );
    });
  });

  describe('endOfentralDirectoryRecords', () => {
    it('standard', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = false;
      const eocdrBuffer = zipWriter.writeEndOfCentralDirectoryRecord(2, 200, 2000);
      expect(encodeArrayBuffer(eocdrBuffer)).to.equal('UEsFBgAAAAACAAIAyAAAANAHAAAAAA==');
    });
    it('zip64', () => {
      const zipWriter = new ZipWriter();
      zipWriter.zip64 = true;
      const eocdrBuffer = zipWriter.writeEndOfCentralDirectoryRecord(2, 200, 2000);
      expect(encodeArrayBuffer(eocdrBuffer)).to.equal(
        'UEsGBiwAAAAAAAAAPwMtAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAMgAAAAAAAAA0AcAAAAAAABQSwYHAAAAAJgIAAAAAAAAAQAAAFBLBQYAAAAA////////////////AAA='
      );
    });
  });
});

describe('reader', () => {
  const manifestEntry = (uncompressedSize: number) =>
    [
      {
        fileName: '0.manifest.json',
        relativeOffsetOfLocalHeader: 0,
        headerLength: 1024,
        uncompressedSize,
      } as CentralDirectory,
    ] as const;

  it('fails on bad manifest size', async () => {
    const reader = new ZipReader(() => Promise.resolve(new Uint8Array([])));
    let message = '';
    try {
      await reader.getManifest([...manifestEntry(MANIFEST_MAX_SIZE + 1)], '0.manifest.json');
      expect.fail('expected an oversized manifest to be rejected');
    } catch (e) {
      message = e instanceof Error ? e.message : String(e);
    }
    expect(message).to.contain('too large');
  });

  // A reader configured with a tighter budget than the default must enforce
  // its own, otherwise the write side has no way to guarantee readability for
  // a constrained consumer.
  it('honours a configured manifest ceiling', async () => {
    const manifestMaxSize = 4096;
    const reader = new ZipReader(() => Promise.resolve(new Uint8Array([])), { manifestMaxSize });
    let message = '';
    try {
      await reader.getManifest([...manifestEntry(manifestMaxSize + 1)], '0.manifest.json');
      expect.fail('expected the configured ceiling to be enforced');
    } catch (e) {
      message = e instanceof Error ? e.message : String(e);
    }
    expect(message).to.contain('too large');
    expect(message).to.contain('4 KiB limit');
  });
});
