// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file entityresolution/entity_resolution.proto (package entityresolution, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ResolveEntitiesRequest, ResolveEntitiesResponse } from "./entity_resolution_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service entityresolution.EntityResolutionService
 */
export const EntityResolutionService = {
  typeName: "entityresolution.EntityResolutionService",
  methods: {
    /**
     * @generated from rpc entityresolution.EntityResolutionService.ResolveEntities
     */
    resolveEntities: {
      name: "ResolveEntities",
      I: ResolveEntitiesRequest,
      O: ResolveEntitiesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

