/**
 * @fileoverview gRPC-Web generated client stub for policy.attributes
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: policy/attributes/attributes.proto

/* eslint-disable */
// @ts-nocheck

import * as grpcWeb from 'grpc-web';

import * as policy_attributes_attributes_pb from '../../policy/attributes/attributes_pb'; // proto import: "policy/attributes/attributes.proto"

export class AttributesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string };
  options_: null | { [index: string]: any };

  constructor(
    hostname: string,
    credentials?: null | { [index: string]: string },
    options?: null | { [index: string]: any }
  ) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListAttributes = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/ListAttributes',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.ListAttributesRequest,
    policy_attributes_attributes_pb.ListAttributesResponse,
    (request: policy_attributes_attributes_pb.ListAttributesRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.ListAttributesResponse.deserializeBinary
  );

  listAttributes(
    request: policy_attributes_attributes_pb.ListAttributesRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.ListAttributesResponse>;

  listAttributes(
    request: policy_attributes_attributes_pb.ListAttributesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.ListAttributesResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.ListAttributesResponse>;

  listAttributes(
    request: policy_attributes_attributes_pb.ListAttributesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.ListAttributesResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/ListAttributes',
        request,
        metadata || {},
        this.methodDescriptorListAttributes,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/ListAttributes',
      request,
      metadata || {},
      this.methodDescriptorListAttributes
    );
  }

  methodDescriptorListAttributeValues = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/ListAttributeValues',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.ListAttributeValuesRequest,
    policy_attributes_attributes_pb.ListAttributeValuesResponse,
    (request: policy_attributes_attributes_pb.ListAttributeValuesRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.ListAttributeValuesResponse.deserializeBinary
  );

  listAttributeValues(
    request: policy_attributes_attributes_pb.ListAttributeValuesRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.ListAttributeValuesResponse>;

  listAttributeValues(
    request: policy_attributes_attributes_pb.ListAttributeValuesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.ListAttributeValuesResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.ListAttributeValuesResponse>;

  listAttributeValues(
    request: policy_attributes_attributes_pb.ListAttributeValuesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.ListAttributeValuesResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/ListAttributeValues',
        request,
        metadata || {},
        this.methodDescriptorListAttributeValues,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/ListAttributeValues',
      request,
      metadata || {},
      this.methodDescriptorListAttributeValues
    );
  }

  methodDescriptorGetAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/GetAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.GetAttributeRequest,
    policy_attributes_attributes_pb.GetAttributeResponse,
    (request: policy_attributes_attributes_pb.GetAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.GetAttributeResponse.deserializeBinary
  );

  getAttribute(
    request: policy_attributes_attributes_pb.GetAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.GetAttributeResponse>;

  getAttribute(
    request: policy_attributes_attributes_pb.GetAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.GetAttributeResponse>;

  getAttribute(
    request: policy_attributes_attributes_pb.GetAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/GetAttribute',
        request,
        metadata || {},
        this.methodDescriptorGetAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/GetAttribute',
      request,
      metadata || {},
      this.methodDescriptorGetAttribute
    );
  }

  methodDescriptorGetAttributeValuesByFqns = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/GetAttributeValuesByFqns',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.GetAttributeValuesByFqnsRequest,
    policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse,
    (request: policy_attributes_attributes_pb.GetAttributeValuesByFqnsRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse.deserializeBinary
  );

  getAttributeValuesByFqns(
    request: policy_attributes_attributes_pb.GetAttributeValuesByFqnsRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse>;

  getAttributeValuesByFqns(
    request: policy_attributes_attributes_pb.GetAttributeValuesByFqnsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse>;

  getAttributeValuesByFqns(
    request: policy_attributes_attributes_pb.GetAttributeValuesByFqnsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeValuesByFqnsResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/GetAttributeValuesByFqns',
        request,
        metadata || {},
        this.methodDescriptorGetAttributeValuesByFqns,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/GetAttributeValuesByFqns',
      request,
      metadata || {},
      this.methodDescriptorGetAttributeValuesByFqns
    );
  }

  methodDescriptorCreateAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/CreateAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.CreateAttributeRequest,
    policy_attributes_attributes_pb.CreateAttributeResponse,
    (request: policy_attributes_attributes_pb.CreateAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.CreateAttributeResponse.deserializeBinary
  );

  createAttribute(
    request: policy_attributes_attributes_pb.CreateAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.CreateAttributeResponse>;

  createAttribute(
    request: policy_attributes_attributes_pb.CreateAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.CreateAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.CreateAttributeResponse>;

  createAttribute(
    request: policy_attributes_attributes_pb.CreateAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.CreateAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/CreateAttribute',
        request,
        metadata || {},
        this.methodDescriptorCreateAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/CreateAttribute',
      request,
      metadata || {},
      this.methodDescriptorCreateAttribute
    );
  }

  methodDescriptorUpdateAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/UpdateAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.UpdateAttributeRequest,
    policy_attributes_attributes_pb.UpdateAttributeResponse,
    (request: policy_attributes_attributes_pb.UpdateAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.UpdateAttributeResponse.deserializeBinary
  );

  updateAttribute(
    request: policy_attributes_attributes_pb.UpdateAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.UpdateAttributeResponse>;

  updateAttribute(
    request: policy_attributes_attributes_pb.UpdateAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.UpdateAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.UpdateAttributeResponse>;

  updateAttribute(
    request: policy_attributes_attributes_pb.UpdateAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.UpdateAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/UpdateAttribute',
        request,
        metadata || {},
        this.methodDescriptorUpdateAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/UpdateAttribute',
      request,
      metadata || {},
      this.methodDescriptorUpdateAttribute
    );
  }

  methodDescriptorDeactivateAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/DeactivateAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.DeactivateAttributeRequest,
    policy_attributes_attributes_pb.DeactivateAttributeResponse,
    (request: policy_attributes_attributes_pb.DeactivateAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.DeactivateAttributeResponse.deserializeBinary
  );

  deactivateAttribute(
    request: policy_attributes_attributes_pb.DeactivateAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.DeactivateAttributeResponse>;

  deactivateAttribute(
    request: policy_attributes_attributes_pb.DeactivateAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.DeactivateAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.DeactivateAttributeResponse>;

  deactivateAttribute(
    request: policy_attributes_attributes_pb.DeactivateAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.DeactivateAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/DeactivateAttribute',
        request,
        metadata || {},
        this.methodDescriptorDeactivateAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/DeactivateAttribute',
      request,
      metadata || {},
      this.methodDescriptorDeactivateAttribute
    );
  }

  methodDescriptorGetAttributeValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/GetAttributeValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.GetAttributeValueRequest,
    policy_attributes_attributes_pb.GetAttributeValueResponse,
    (request: policy_attributes_attributes_pb.GetAttributeValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.GetAttributeValueResponse.deserializeBinary
  );

  getAttributeValue(
    request: policy_attributes_attributes_pb.GetAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.GetAttributeValueResponse>;

  getAttributeValue(
    request: policy_attributes_attributes_pb.GetAttributeValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.GetAttributeValueResponse>;

  getAttributeValue(
    request: policy_attributes_attributes_pb.GetAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.GetAttributeValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/GetAttributeValue',
        request,
        metadata || {},
        this.methodDescriptorGetAttributeValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/GetAttributeValue',
      request,
      metadata || {},
      this.methodDescriptorGetAttributeValue
    );
  }

  methodDescriptorCreateAttributeValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/CreateAttributeValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.CreateAttributeValueRequest,
    policy_attributes_attributes_pb.CreateAttributeValueResponse,
    (request: policy_attributes_attributes_pb.CreateAttributeValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.CreateAttributeValueResponse.deserializeBinary
  );

  createAttributeValue(
    request: policy_attributes_attributes_pb.CreateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.CreateAttributeValueResponse>;

  createAttributeValue(
    request: policy_attributes_attributes_pb.CreateAttributeValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.CreateAttributeValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.CreateAttributeValueResponse>;

  createAttributeValue(
    request: policy_attributes_attributes_pb.CreateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.CreateAttributeValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/CreateAttributeValue',
        request,
        metadata || {},
        this.methodDescriptorCreateAttributeValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/CreateAttributeValue',
      request,
      metadata || {},
      this.methodDescriptorCreateAttributeValue
    );
  }

  methodDescriptorUpdateAttributeValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/UpdateAttributeValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.UpdateAttributeValueRequest,
    policy_attributes_attributes_pb.UpdateAttributeValueResponse,
    (request: policy_attributes_attributes_pb.UpdateAttributeValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.UpdateAttributeValueResponse.deserializeBinary
  );

  updateAttributeValue(
    request: policy_attributes_attributes_pb.UpdateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.UpdateAttributeValueResponse>;

  updateAttributeValue(
    request: policy_attributes_attributes_pb.UpdateAttributeValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.UpdateAttributeValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.UpdateAttributeValueResponse>;

  updateAttributeValue(
    request: policy_attributes_attributes_pb.UpdateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.UpdateAttributeValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/UpdateAttributeValue',
        request,
        metadata || {},
        this.methodDescriptorUpdateAttributeValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/UpdateAttributeValue',
      request,
      metadata || {},
      this.methodDescriptorUpdateAttributeValue
    );
  }

  methodDescriptorDeactivateAttributeValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/DeactivateAttributeValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.DeactivateAttributeValueRequest,
    policy_attributes_attributes_pb.DeactivateAttributeValueResponse,
    (request: policy_attributes_attributes_pb.DeactivateAttributeValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.DeactivateAttributeValueResponse.deserializeBinary
  );

  deactivateAttributeValue(
    request: policy_attributes_attributes_pb.DeactivateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.DeactivateAttributeValueResponse>;

  deactivateAttributeValue(
    request: policy_attributes_attributes_pb.DeactivateAttributeValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.DeactivateAttributeValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.DeactivateAttributeValueResponse>;

  deactivateAttributeValue(
    request: policy_attributes_attributes_pb.DeactivateAttributeValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.DeactivateAttributeValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/DeactivateAttributeValue',
        request,
        metadata || {},
        this.methodDescriptorDeactivateAttributeValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/DeactivateAttributeValue',
      request,
      metadata || {},
      this.methodDescriptorDeactivateAttributeValue
    );
  }

  methodDescriptorAssignKeyAccessServerToAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/AssignKeyAccessServerToAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeRequest,
    policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse,
    (request: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse.deserializeBinary
  );

  assignKeyAccessServerToAttribute(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse>;

  assignKeyAccessServerToAttribute(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse>;

  assignKeyAccessServerToAttribute(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.AssignKeyAccessServerToAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/AssignKeyAccessServerToAttribute',
        request,
        metadata || {},
        this.methodDescriptorAssignKeyAccessServerToAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/AssignKeyAccessServerToAttribute',
      request,
      metadata || {},
      this.methodDescriptorAssignKeyAccessServerToAttribute
    );
  }

  methodDescriptorRemoveKeyAccessServerFromAttribute = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/RemoveKeyAccessServerFromAttribute',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeRequest,
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse,
    (request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse.deserializeBinary
  );

  removeKeyAccessServerFromAttribute(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse>;

  removeKeyAccessServerFromAttribute(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse>;

  removeKeyAccessServerFromAttribute(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.RemoveKeyAccessServerFromAttributeResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/RemoveKeyAccessServerFromAttribute',
        request,
        metadata || {},
        this.methodDescriptorRemoveKeyAccessServerFromAttribute,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/RemoveKeyAccessServerFromAttribute',
      request,
      metadata || {},
      this.methodDescriptorRemoveKeyAccessServerFromAttribute
    );
  }

  methodDescriptorAssignKeyAccessServerToValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/AssignKeyAccessServerToValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.AssignKeyAccessServerToValueRequest,
    policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse,
    (request: policy_attributes_attributes_pb.AssignKeyAccessServerToValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse.deserializeBinary
  );

  assignKeyAccessServerToValue(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse>;

  assignKeyAccessServerToValue(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse>;

  assignKeyAccessServerToValue(
    request: policy_attributes_attributes_pb.AssignKeyAccessServerToValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.AssignKeyAccessServerToValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/AssignKeyAccessServerToValue',
        request,
        metadata || {},
        this.methodDescriptorAssignKeyAccessServerToValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/AssignKeyAccessServerToValue',
      request,
      metadata || {},
      this.methodDescriptorAssignKeyAccessServerToValue
    );
  }

  methodDescriptorRemoveKeyAccessServerFromValue = new grpcWeb.MethodDescriptor(
    '/policy.attributes.AttributesService/RemoveKeyAccessServerFromValue',
    grpcWeb.MethodType.UNARY,
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueRequest,
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse,
    (request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueRequest) => {
      return request.serializeBinary();
    },
    policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse.deserializeBinary
  );

  removeKeyAccessServerFromValue(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueRequest,
    metadata?: grpcWeb.Metadata | null
  ): Promise<policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse>;

  removeKeyAccessServerFromValue(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse
    ) => void
  ): grpcWeb.ClientReadableStream<policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse>;

  removeKeyAccessServerFromValue(
    request: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (
      err: grpcWeb.RpcError,
      response: policy_attributes_attributes_pb.RemoveKeyAccessServerFromValueResponse
    ) => void
  ) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ + '/policy.attributes.AttributesService/RemoveKeyAccessServerFromValue',
        request,
        metadata || {},
        this.methodDescriptorRemoveKeyAccessServerFromValue,
        callback
      );
    }
    return this.client_.unaryCall(
      this.hostname_ + '/policy.attributes.AttributesService/RemoveKeyAccessServerFromValue',
      request,
      metadata || {},
      this.methodDescriptorRemoveKeyAccessServerFromValue
    );
  }
}
