// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts,import_extension=none"
// @generated from file policy/attributes/attributes.proto (package policy.attributes, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AssignKeyAccessServerToAttributeRequest, AssignKeyAccessServerToAttributeResponse, AssignKeyAccessServerToValueRequest, AssignKeyAccessServerToValueResponse, CreateAttributeRequest, CreateAttributeResponse, CreateAttributeValueRequest, CreateAttributeValueResponse, DeactivateAttributeRequest, DeactivateAttributeResponse, DeactivateAttributeValueRequest, DeactivateAttributeValueResponse, GetAttributeRequest, GetAttributeResponse, GetAttributeValueRequest, GetAttributeValueResponse, GetAttributeValuesByFqnsRequest, GetAttributeValuesByFqnsResponse, ListAttributesRequest, ListAttributesResponse, ListAttributeValuesRequest, ListAttributeValuesResponse, RemoveKeyAccessServerFromAttributeRequest, RemoveKeyAccessServerFromAttributeResponse, RemoveKeyAccessServerFromValueRequest, RemoveKeyAccessServerFromValueResponse, UpdateAttributeRequest, UpdateAttributeResponse, UpdateAttributeValueRequest, UpdateAttributeValueResponse } from "./attributes_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * /
 * / Attribute Service
 * /
 *
 * @generated from service policy.attributes.AttributesService
 */
export const AttributesService = {
  typeName: "policy.attributes.AttributesService",
  methods: {
    /**
     * --------------------------------------*
     * Attribute RPCs
     * ---------------------------------------
     *
     * @generated from rpc policy.attributes.AttributesService.ListAttributes
     */
    listAttributes: {
      name: "ListAttributes",
      I: ListAttributesRequest,
      O: ListAttributesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.ListAttributeValues
     */
    listAttributeValues: {
      name: "ListAttributeValues",
      I: ListAttributeValuesRequest,
      O: ListAttributeValuesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.GetAttribute
     */
    getAttribute: {
      name: "GetAttribute",
      I: GetAttributeRequest,
      O: GetAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.GetAttributeValuesByFqns
     */
    getAttributeValuesByFqns: {
      name: "GetAttributeValuesByFqns",
      I: GetAttributeValuesByFqnsRequest,
      O: GetAttributeValuesByFqnsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.CreateAttribute
     */
    createAttribute: {
      name: "CreateAttribute",
      I: CreateAttributeRequest,
      O: CreateAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.UpdateAttribute
     */
    updateAttribute: {
      name: "UpdateAttribute",
      I: UpdateAttributeRequest,
      O: UpdateAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.DeactivateAttribute
     */
    deactivateAttribute: {
      name: "DeactivateAttribute",
      I: DeactivateAttributeRequest,
      O: DeactivateAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * --------------------------------------*
     * Value RPCs
     * ---------------------------------------
     *
     * @generated from rpc policy.attributes.AttributesService.GetAttributeValue
     */
    getAttributeValue: {
      name: "GetAttributeValue",
      I: GetAttributeValueRequest,
      O: GetAttributeValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.CreateAttributeValue
     */
    createAttributeValue: {
      name: "CreateAttributeValue",
      I: CreateAttributeValueRequest,
      O: CreateAttributeValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.UpdateAttributeValue
     */
    updateAttributeValue: {
      name: "UpdateAttributeValue",
      I: UpdateAttributeValueRequest,
      O: UpdateAttributeValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.DeactivateAttributeValue
     */
    deactivateAttributeValue: {
      name: "DeactivateAttributeValue",
      I: DeactivateAttributeValueRequest,
      O: DeactivateAttributeValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * --------------------------------------*
     * Attribute <> Key Access Server RPCs
     * ---------------------------------------
     *
     * @generated from rpc policy.attributes.AttributesService.AssignKeyAccessServerToAttribute
     */
    assignKeyAccessServerToAttribute: {
      name: "AssignKeyAccessServerToAttribute",
      I: AssignKeyAccessServerToAttributeRequest,
      O: AssignKeyAccessServerToAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.RemoveKeyAccessServerFromAttribute
     */
    removeKeyAccessServerFromAttribute: {
      name: "RemoveKeyAccessServerFromAttribute",
      I: RemoveKeyAccessServerFromAttributeRequest,
      O: RemoveKeyAccessServerFromAttributeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.AssignKeyAccessServerToValue
     */
    assignKeyAccessServerToValue: {
      name: "AssignKeyAccessServerToValue",
      I: AssignKeyAccessServerToValueRequest,
      O: AssignKeyAccessServerToValueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc policy.attributes.AttributesService.RemoveKeyAccessServerFromValue
     */
    removeKeyAccessServerFromValue: {
      name: "RemoveKeyAccessServerFromValue",
      I: RemoveKeyAccessServerFromValueRequest,
      O: RemoveKeyAccessServerFromValueResponse,
      kind: MethodKind.Unary,
    },
  }
};

