name: "Deliver Client to npm registry"

on:
  push:
    branches:
      - main
      - "release/**"
  release:
    types:
      - created

# Default empty permissions for all jobs
permissions: {}

jobs:
  deliver:
    permissions:
      contents: write
      packages: read
    uses: opentdf/web-sdk/.github/workflows/reusable_deliver.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
