name: "Release"

on:
  workflow_call: {}
  push:
    branches:
      - main
      - "release/*"

# Default empty permissions for all jobs
permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: opentdf/platform/.github/workflows/reusable_release-please.yaml@main
