name: Release

on:
  push:
    branches:
      - main
      - "release/**"

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: opentdf/platform/.github/workflows/reusable_release-please.yaml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      AUTOMATION_KEY: ${{ secrets.AUTOMATION_KEY }}

  update-dependencies:
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Generate a token"
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.AUTOMATION_KEY }}

      - name: "Checkout repo"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
          ref: ${{ fromJSON(needs.release-please.outputs.prs)[0].headBranchName }}

      - name: "Update dependencies"
        run: |
          git config --global user.name "opentdf-automation[bot]"
          git config --global user.email "149537512+opentdf-automation[bot]@users.noreply.github.com"
          make all
          git add .
          git commit -m "Update dependencies"
          git push

      - name: "Sign 'Update dependencies' commit"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_NUMBERS: ${{ fromJSON(needs.release-please.outputs.prs)[0].number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        uses: opentdf/platform/.github/actions/sign-backport-action-commits@main
