name: Release

on:
  push:
    branches:
      - main
      - "release/**"

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: opentdf/platform/.github/workflows/reusable_release-please.yaml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      AUTOMATION_KEY: ${{ secrets.AUTOMATION_KEY }}
  fix-versions:
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "fasd"
        run: |
          echo "PRs created: ${{ needs.release-please.outputs.prs_created }}"

